##########################################################
## FastQ Screen configuration — rnaseq2tracksP
##########################################################

THREADS         4
BOWTIE2         bowtie2

DATABASE Mouse        /home/micgdu/GenomicData/fastq_screen_db/mouse/mouse
DATABASE Human        /home/micgdu/GenomicData/fastq_screen_db/human/human
DATABASE Zebrafish    /home/micgdu/GenomicData/fastq_screen_db/zebrafish/zebrafish
DATABASE Drosophila   /home/micgdu/GenomicData/fastq_screen_db/drosophila/drosophila
DATABASE Mycoplasma   /home/micgdu/GenomicData/fastq_screen_db/mycoplasma/mycoplasma
